### ISSUE TITLE
[bug]Some concave shapes will fall into other when fall down.

### ISSUE THREAD

**Issue by guawoo** [schteppe/p2.js#326]
![bug](https://user-images.githubusercontent.com/9428661/40340604-6fddf216-5db2-11e8-97d9-36148abfd9fa.gif)

This is werid case, I have no idea to deal it.

**Comment by jtenner** [comment]
Hi @guawoo.

Have you tried using the `Body` parameter `ccdSpeedThreshold`?

It's default value is `-1`, and it is disabled by default. If you need high resolution impacts, because objects are moving very fast, set it to 0 in your `Body` constructor, and that should fix the problem.

```js
const body = new Body({
  ...,
  ccdSpeedThreshold: 0,
  ...
});
```

Note, you may have to use the github version of `p2.js` by installing it via npm using:
 ```
npm install --save schteppe/p2.js
```

**Comment by guawoo** [comment]
@jtenner 
Thank you so much, I have to set ccSpeedTreshold to 0 and use github version,but this case still appear. It is not normal appearance, need to special shapes and special positions like gif in. :(

**Comment by jtenner** [comment]
Can you please replicate the problem with an online environment like codepen?

**Comment by schteppe** [comment]
This bug is probably fixed after adding [polygon clipping](https://github.com/schteppe/p2.js/commit/7387dcd0bef76b89b67c0137309f83e6a69e37d9). Could you try getting the latest master branch, rebuilding the library and see if it works better? Thanks.
